name: Bug report [EN]
description: Reporting a bug.
labels:
- bug
body:
- type: markdown
  attributes:
    value: 'Thanks for taking the time to fill out this bug report!

      Please make sure to read our [Wiki Page](https://github.com/Courseplay/Courseplay_FS25/wiki)
      before creating a new issue!

      You can also find our in-game help pages on the [Courseplay website](https://courseplay.github.io/CourseplayHelpFS25/),
      which includes lots of useful information that may help with your problem.

      '
- type: dropdown
  id: mod-version
  attributes:
    label: Version
    description: Which CoursePlay version are you using?
    options:
    - '0'
    - 8.0.0.0
    - 8.0.0.1
    - 8.0.0.2
    - 8.0.0.3
    - 8.0.0.4
    - 8.0.0.5
    - 8.0.0.6
    - 8.0.0.7
    - 8.0.0.8
    - 8.0.0.9
    - 8.0.0.10
    - 8.0.0.11
    - 8.0.0.12
    - 8.0.1.0
    - 8.0.1.1
    - 8.0.1.2
    - 8.0.1.3
    - 8.0.1.4
    - 8.0.1.5
    - 8.0.2.0
    - 8.0.2.1
    - 8.0.2.2
    - 8.0.2.3
    - 8.1.0.0
    default: 24
  validations:
    required: true
- type: dropdown
  id: game-version
  attributes:
    label: Game Version
    description: What version of the game are you playing?
    options:
    - 1.4.0.0
    - 1.5.0.0
    - 1.5.0.1
    - 1.6.0.0
    - 1.7.0.1
    - 1.7.0.2
    - 1.8.0.1
    - 1.9.0.1
    - 1.10.0.0
    default: 8
  validations:
    required: true
- type: dropdown
  id: spmp
  attributes:
    label: SP/MP
    description: Did the bug happen in SP or MP?
    options:
    - SP (Singleplayer)
    - MP (Multiplayer)
    default: 0
  validations:
    required: true
- type: textarea
  id: what-happened
  attributes:
    label: What happened?
    description: Please describe what happened.
    placeholder: Tell us what you see!
  validations:
    required: true
- type: textarea
  id: how-to
  attributes:
    label: How can we reproduce this?
    description: If you can, please describe the steps to reproduce this bug.
    placeholder: Describe as good as possible.
  validations:
    required: true
- type: textarea
  id: expect
  attributes:
    label: What did you expect to happen?
    description: What  did you expect to happen when you tried that function and the
      bug occurred.
    placeholder: Describe as good as possible.
  validations:
    required: true
- type: textarea
  id: logs
  attributes:
    label: Attach your log.txt!
    description: Use drag and drop into the textbox to upload the log.txt into the
      text field or use [Gist](https://gist.github.com/) or [Pastebin](http://pastebin.com/).
    placeholder: Please add your log.txt from file path ("C:\\Users\\<USER_NAME>\\Documents\\My
      Games\\FarmingSimulator2025\\log.txt").
  validations:
    required: true
- type: textarea
  id: screenshots
  attributes:
    label: Screenshots
    description: Use drag and drop into the textbox to upload the screenshots.
    placeholder: If you have any helpful screenshots to describe your situation, please
      add them here.
  validations:
    required: true
