name: Question [EN]
description: You got a question? Just ask!
labels:
- question
body:
- type: markdown
  attributes:
    value: 'Please use this template to ask your question!

      Please make sure to read our [Wiki Page](https://github.com/Courseplay/Courseplay_FS25/wiki)
      before creating a new issue!

      Our help pages from the game can also be found at [Courseplay.dev]!(https://courseplay.github.io/Courseplay_FS22.github.io/),
      there you can check out many informations before asking a qustion!

      '
- type: dropdown
  id: mod-version
  attributes:
    label: Version
    description: Which CoursePlay version are you using?
    options:
    - '0'
    - 8.0.0.0
    - 8.0.0.1
    - 8.0.0.2
    - 8.0.0.3
    - 8.0.0.4
    - 8.0.0.5
    - 8.0.0.6
    - 8.0.0.7
    - 8.0.0.8
    - 8.0.0.9
    - 8.0.0.10
    - 8.0.0.11
    - 8.0.0.12
    - 8.0.1.0
    - 8.0.1.1
    - 8.0.1.2
    default: 16
  validations:
    required: true
- type: dropdown
  id: spmp
  attributes:
    label: SP/MP
    description: Did the bug happen in SP or MP?
    options:
    - SP (Singleplayer)
    - MP (Multiplayer)
    default: 0
  validations:
    required: true
- type: dropdown
  id: about
  attributes:
    label: What is your question about?
    description: Select a category.
    options:
    - Course creation
    - Vehicle settings
    - Global CP settings
    - more later
    default: 0
  validations:
    required: true
- type: textarea
  id: question
  attributes:
    label: What is your question?
    description: Question
    placeholder: Question
  validations:
    required: true
- type: textarea
  id: screenshots
  attributes:
    label: Screenshots
    description: Use drag and drop into the textbox to upload the screenshots.
    placeholder: If you have any helpful screenshots to describe the situation, please
      add them here.
  validations:
    required: true
