name: Feature Idea/Request [EN]
description: A feature request or Idea.
labels:
- Suggestion
body:
- type: markdown
  attributes:
    value: 'Thanks for taking the time to fill out this report!

      Please make sure to read our [Wiki Page](https://github.com/Courseplay/Courseplay_FS25/wiki)
      before creating a new issue!

      '
- type: dropdown
  id: mod-version
  attributes:
    label: Version
    description: Which CoursePlay version are you using?
    options:
    - '0'
    - 8.0.0.0
    - 8.0.0.1
    - 8.0.0.2
    - 8.0.0.3
    - 8.0.0.4
    - 8.0.0.5
    - 8.0.0.6
    - 8.0.0.7
    - 8.0.0.8
    - 8.0.0.9
    - 8.0.0.10
    - 8.0.0.11
    - 8.0.0.12
    - 8.0.1.0
    - 8.0.1.1
    - 8.0.1.2
    - 8.0.1.3
    - 8.0.1.4
    - 8.0.1.5
    - 8.0.2.0
    - 8.0.2.1
    - 8.0.2.2
    - 8.0.2.3
    default: 23
  validations:
    required: true
- type: dropdown
  id: spmp
  attributes:
    label: SP/MP
    description: Is your idea for SP oder MP?
    options:
    - SP (Singleplayer)
    - MP (Multiplayer)
    default: 0
  validations:
    required: true
- type: textarea
  id: what-does
  attributes:
    label: What can be done with your idea?
    description: Please describe as good as possible the problem your idea solves.
    placeholder: Describe as good as possible.
  validations:
    required: true
- type: textarea
  id: how-to
  attributes:
    label: If applicable, how would the user interface look like for this enhancement?
    description: Describe the solution you'd like.
    placeholder: Describe as good as possible.
  validations:
    required: true
- type: textarea
  id: alternative
  attributes:
    label: Is there an alternative?
    description: Are there any alternatives you've considered?
    placeholder: Describe as good as possible.
  validations:
    required: true
- type: textarea
  id: screenshots
  attributes:
    label: Screenshots
    description: Use drag and drop into the textbox to upload the screenshots.
    placeholder: If you have any helpful screenshots to describe your idea, please
      add them here.
  validations:
    required: true
